name: PR Build and Tests

on:
  pull_request:
    branches:
      - main

jobs:
    build_and_tests:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
          with:
            submodules: true

        - name: Install dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y cmake ninja-build clang-format

        - name: Run clang-format
          run: |
            git ls-files | grep -E '\.(c|h|cpp|hpp)$' | xargs clang-format -n --Werror

        - name: Example build
          run: |
            cd examples
            cmake -S . -B build -G Ninja
            cmake --build build

        - name: Build and run unit tests
          run: |
            cmake -S . -B build -G Ninja
            cmake --build build
            ./build/tests/nn_cli_test

        - name: Install dependencies for integration tests
          run: |
            pip3 install -r tests/integration/requirements.txt

        - name: Run integration tests
          run: |
            cd tests/
            pytest -vs integration
